const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const {ROUTES:privateRoutes,TIMETABLE:privateTimetable,PROFILE:privateProfile}=require('./test-fixtures.cjs');
test('walking view applies every meaningful step in every map orientation',()=>{
 for(const [zoom,bearing] of [[17,-90],[16,0],[15,0],[16,-90]]){
  const c=context();c.zoom=zoom;c.bearing=bearing;
  const result=vm.runInContext(`(()=>{const views=[],rotations=[],map={setView(p,z,o){views.push({p:[...p],z,o})},setBearing(b){rotations.push(b)}};let state=null;for(let i=0;i<=12;i++)state=updateMapViewport(map,state,[i/111195,0],zoom,bearing);return JSON.stringify({views,rotations});})()`,c);
  const {views,rotations}=JSON.parse(result);
  assert.equal(views.length,13);assert.equal(views.at(-1).p[0],12/111195);
  assert(views.every(v=>v.z===zoom&&v.o.animate===false));assert.equal(rotations.length,1);
 }
});
test('bearing and movement updates remain independent and continuous',()=>{
 const c=context();const result=JSON.parse(vm.runInContext(`(()=>{let moves=0;const bearings=[],map={setView(){moves++},setBearing(b){bearings.push(b)}};let s=updateMapViewport(map,null,[0,0],17,0);for(let i=1;i<=3;i++)s=updateMapViewport(map,s,[i/111195,0],17,i%2?-.5:0);s=updateMapViewport(map,s,[4/111195,0],17,-1);s=updateMapViewport(map,s,[4/111195,0],17,-2);s=updateMapViewport(map,s,[4/111195,0],17,-3);return JSON.stringify({moves,bearings});})()`,c));
 assert.equal(result.moves,5);assert.deepEqual(result.bearings,[0,-.5,0,-.5,-1,-2,-3]);
});
test('viewport resets, wraparound bearings and zoom swaps apply immediately',()=>{
 const c=context();const result=JSON.parse(vm.runInContext(`(()=>{let moves=0,rotations=0;const map={setView(){moves++},setBearing(){rotations++}};let s=updateMapViewport(map,null,[0,0],17,-359);s=updateMapViewport(map,s,[0,0],17,0);s=updateMapViewport(map,s,[0,0],16,0);s=updateMapViewport(map,null,[0,0],16,0);return JSON.stringify({moves,rotations});})()`,c));
 assert.deepEqual(result,{moves:3,rotations:4});
});
function context(){const elements={app:{innerHTML:''},'journey-status':{},toast:{classList:{add(){},remove(){}}},dialog:{addEventListener(){},open:false}},listeners=[],window={scrollX:0,scrollY:0,scrollCalls:[],scrollTo(options){this.scrollCalls.push(options);this.scrollX=options.left??0;this.scrollY=options.top??0;},requestAnimationFrame(fn){fn();},addEventListener(){}};const c={structuredClone,Date,AbortSignal,console,ROUTES:structuredClone(privateRoutes),TIMETABLE:structuredClone(privateTimetable),STEADY_PROFILE:structuredClone(privateProfile),fetch:async()=>({ok:true,json:async()=>({timetable:null,stale:true})}),document:{getElementById:id=>elements[id]||null,addEventListener:(...a)=>listeners.push(a),querySelectorAll:()=>[],querySelector:()=>null},localStorage:{getItem:()=>null},window,navigator:{geolocation:{watchPosition(){return 1},clearWatch(){}}},setTimeout(){},setInterval(){return 1},clearInterval(){},isSharedFollower:()=>false,takeLocalControl(){},syncWrite(){},journeySnapshot:()=>({}),readyToLeave:async()=>{},shared:{},deviceId:'device-123'};vm.createContext(c);for(const name of ['planner','navigation','simulation','tracking','reminders','app','companion'])vm.runInContext(fs.readFileSync('public/'+name+'.js','utf8'),c);return c;}
test('background navigation renders preserve the current scroll position',()=>{const c=context();c.window.scrollCalls.length=0;c.window.scrollY=720;vm.runInContext('render()',c);assert(c.window.scrollCalls.length>=1);assert.equal(c.window.scrollCalls.at(-1).top,720);});
test('stop code is compressed into the active stop and persists while waiting',()=>{const c=context();for(const direction of [0,1])for(const step of [0,1]){const html=vm.runInContext(`selected=${direction};view='trip';forceDemoBus=true;liveMode=false;resetDemo(${step});trip()`,c);assert(html.includes(direction===0?'TA1':'TB1'));assert(html.includes('stop-code-inline'));assert(!html.includes('Check the sign'));assert(!html.includes('On older signs'));}});
test('active navigation removes top chrome and moves controls below the map',()=>{const c=context(),html=vm.runInContext("selected=1;view='trip';resetDemo(0);header()+trip()",c);assert(!html.includes('topbar'));assert(html.indexOf('journey-map')<html.indexOf('active-nav-footer'));assert(html.indexOf('active-journey-label')<html.indexOf('id="stage-title"'));});
test('map swap recentres and assigns viewport-specific zoom levels',()=>{const source=fs.readFileSync('public/companion.js','utf8'),app=fs.readFileSync('public/app.js','utf8');assert(source.includes("routeMap.setView(n.point,routeMap.getZoom()"));assert(source.includes('zoom=northMain?16:17'));assert(source.includes('n.point,northMain?16:15'));assert(app.includes("retainedMini=view==='trip'?document.getElementById('mini-map')"));});
test('maps disable manual movement and tile fades',()=>{const navigation=fs.readFileSync('public/navigation.js','utf8'),companion=fs.readFileSync('public/companion.js','utf8'),css=fs.readFileSync('public/style.css','utf8');for(const source of [navigation,companion]){assert(source.includes('dragging:false'));assert(source.includes('touchZoom:false'));assert(source.includes('fadeAnimation:false'));assert(source.includes('keepBuffer:6'));}assert(!navigation.includes('map-recentre'));assert(css.includes('.leaflet-tile,.leaflet-fade-anim .leaflet-tile{opacity:1!important;transition:none!important}'));});
test('ambiguous GPS never claims the correct street side',()=>{const c=context();assert.equal(vm.runInContext(`selected=0;for(let i=0;i<5;i++)assessSide(physicalStop().point,40);sideState`,c),'unconfirmed');assert.equal(vm.runInContext(`for(let i=0;i<3;i++)assessSide(physicalStop().point,1);sideState`,c),'correct');assert.equal(vm.runInContext(`assessSide(ROUTES.journeys[1].legs[1].stops.at(-1).point,1);sideState`,c),'opposite');});
test('live correction and resume cannot start a simulator',()=>{const c=context();assert.equal(vm.runInContext(`liveMode=true;view='trip';simulation=null;resetDemo(1);startAuto();simulation`,c),null);assert.equal(vm.runInContext('stage',c),1);assert.equal(vm.runInContext('tracker.uncertain',c),true);});
test('duplicate or stale phone fixes cannot advance the trip',()=>{const c=context();vm.runInContext(`liveMode=true;view='trip';selected=0;stage=0;tracker.reset();const point=physicalStop().point;const f={timestamp:Date.now()-30000,coords:{latitude:point[0],longitude:point[1],accuracy:5,speed:0,heading:0}};for(let i=0;i<8;i++)onPhoneFix(f);`,c);assert.equal(vm.runInContext('stage',c),0);assert.equal(vm.runInContext('tracker.uncertain',c),true);});
test('arriving-as requires a fresh dated vehicle on the linked preceding trip',()=>{const c=context();assert.equal(vm.runInContext(`TIMETABLE.predecessors.test={id:'previous',route:'734',stopId:'5102'};chosenPlan={id:'test',from:'5102',date:'2026-09-14'};liveData={vehicles:{timestamp:Date.now()/1000,entries:[{tripId:'previous',date:'20260914',timestamp:Date.now()/1000}]}};arrivingAs(chosenPlan)`,c),' (arriving as 734)');assert.equal(vm.runInContext(`liveData.vehicles.entries[0].timestamp-=100;arrivingAs(chosenPlan)`,c),'');});
test('settings render every reminder editor and quarter-hour work preset',()=>{const c=context();const html=vm.runInContext(`draft=structuredClone(config);settings()`,c);assert(html.includes('Reminder to edit'));assert(html.includes('Early reminder'));assert(html.includes('Work start presets'));assert(html.includes('Thursday'));assert(!html.includes('type="time"'));for(const minute of ['00','15','30','45'])assert(html.includes(`<option ${minute==='00'?'selected':''}>${minute}</option>`)||html.includes(`<option >${minute}</option>`));});
