import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import vm from 'node:vm';import {sessionAPI} from './server/sessions.mjs';import fixtures from './test-fixtures.cjs';
function database(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync('drizzle/0000_cultured_rattler.sql','utf8'));return {prepare(sql){return {bind(...args){return {async first(){return sqlite.prepare(sql).get(...args)||null;},async run(){return {meta:{changes:sqlite.prepare(sql).run(...args).changes}};}};}};}};}
const origin='https://steady.test',desktop='desktop-device-0001',phone='phone-device-000001';
const snapshot={selected:0,stage:0,simTime:0,simSpeed:1,auto:false,planDate:'2026-09-10',planTime:'18:00',config:{journeys:[{},{}]},chosenPlan:{id:'123',route:'R1',leaveAt:10,departure:20,arrival:30}};
function request(db,op,version=0,device=desktop,user='user-a',state=snapshot){return sessionAPI(new Request(origin+'/api/session',{method:op?'PUT':'GET',headers:{Authorization:'Bearer firebase-test-token','Origin':origin,'Content-Type':'application/json'},...(op?{body:JSON.stringify({op,version,device,snapshot:state})}:{})}),{DB:db,TEST_AUTH_USER:user});}
test('account isolation, handoff claim and stale writer rejection',async()=>{const db=database();assert.equal((await request(db,'plan')).status,200);assert.equal((await (await request(db,null,0,phone,'user-b')).json()).state,null);const ready=await request(db,'ready',1);assert.equal((await ready.json()).state.phase,'handoff');assert.equal((await request(db,'claim',2,phone)).status,200);assert.equal((await request(db,'progress',2,desktop)).status,409);assert.equal((await request(db,'progress',3,desktop)).status,409);assert.equal((await request(db,'progress',3,phone)).status,200);assert.equal((await request(db,'finish',4,phone)).status,200);});
test('unauthenticated and cross-origin writes are rejected',async()=>{const db=database();assert.equal((await sessionAPI(new Request(origin+'/api/session',{headers:{'oai-authenticated-user-id':'spoofed'}}),{DB:db})).status,401);assert.equal((await sessionAPI(new Request(origin+'/api/session',{method:'PUT',headers:{Authorization:'Bearer firebase-test-token',Origin:'https://elsewhere.test','Content-Type':'application/json'},body:'{}'}),{DB:db,TEST_AUTH_USER:'user-a'})).status,403);});
function client(db,mobile){const elements={app:{innerHTML:''},toast:{classList:{add(){},remove(){}}},dialog:{open:false,addEventListener(){},close(){}}};const document={hidden:false,getElementById:id=>elements[id]||null,querySelectorAll:()=>[],querySelector:()=>null,addEventListener(){},body:{classList:{add(){}}}};const c={console,document,structuredClone,crypto,URLSearchParams,AbortSignal,Date,Intl,setInterval(){},clearInterval(){},setTimeout(){},navigator:{userAgentData:{mobile}},matchMedia:()=>({matches:mobile}),location:{origin,host:'steady.test',search:''},sessionStorage:{getItem:()=>mobile?phone:desktop,setItem(){}},localStorage:{getItem:()=>null,setItem(){}},window:{scrollTo(){},addEventListener(){}},fetch:async(path,options={})=>path==='/api/live'?Response.json({vehicles:null,updates:null}):sessionAPI(new Request(origin+path,{...options,headers:{...options.headers,Authorization:'Bearer firebase-test-token',Origin:origin}}),{DB:db,TEST_AUTH_USER:'user-a'})};const testData=structuredClone(fixtures);c.ROUTES=testData.ROUTES;c.TIMETABLE=testData.TIMETABLE;c.STEADY_PROFILE=testData.PROFILE;vm.createContext(c);for(const file of ['planner','navigation','simulation','tracking','reminders','app','devices'])vm.runInContext(fs.readFileSync('public/'+file+'.js','utf8'),c);return c;}
test('opening the phone automatically starts navigation from a desktop countdown',async()=>{const db=database(),desk=client(db,false);await vm.runInContext('pollSession()',desk);await vm.runInContext(`selected=0;planDate=localDate();planTime='18:00';chosenPlan=estimateService(TIMETABLE.services.find(s=>s.direction===0),planDate,null,Date.now());chosenPlan.leaveAt=Date.now()+600000;chosenPlan.workArrival=chosenPlan.arrival+300000;view='plan';syncWrite('plan')`,desk);const mobile=client(db,true);await vm.runInContext('pollSession()',mobile);assert.equal(vm.runInContext('chosenPlan.id',mobile),vm.runInContext('chosenPlan.id',desk));assert.equal(vm.runInContext('view',mobile),'trip');assert.equal(vm.runInContext('stage',mobile),0);assert.equal(vm.runInContext('auto',mobile),true);assert.equal(vm.runInContext('shared.state.owner',mobile),phone);await vm.runInContext('pollSession()',desk);assert.equal(vm.runInContext('view',desk),'handoff');vm.runInContext('demoTick(5,false)',mobile);await vm.runInContext("syncWrite('progress')",mobile);await vm.runInContext('pollSession()',desk);assert.equal(vm.runInContext('shared.state.simTime',desk),5);});
test('desktop countdown uses Popout timer and has no manual ready control',()=>{const c=client(database(),false),html=vm.runInContext(`selected=0;chosenPlan={id:'123',route:'R1',leaveAt:Date.now()+600000,departure:Date.now()+900000,arrival:Date.now()+1800000};deviceActions()+widgetMarkup()`,c);assert(html.includes('Popout timer'));assert(!html.includes('Ready to leave'));});
test('mobile planning offers a manual Start trip control',()=>{const c=client(database(),true),html=vm.runInContext('deviceActions()',c);assert(html.includes('data-device="ready"'));assert(html.includes('Start trip'));assert(!html.includes('Popout timer'));});
