const PROJECT_ID='steady-transit-nav';
const ISSUER=`https://securetoken.google.com/${PROJECT_ID}`;
const JWKS_URL='https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com';
let keys={value:null,until:0};
const pad=value=>value+'='.repeat((4-value.length%4)%4);
const decode=value=>JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(pad(value.replaceAll('-','+').replaceAll('_','/'))),c=>c.charCodeAt(0))));
const bytes=value=>Uint8Array.from(atob(pad(value.replaceAll('-','+').replaceAll('_','/'))),c=>c.charCodeAt(0));
async function publicKeys(){if(keys.value&&keys.until>Date.now())return keys.value;const response=await fetch(JWKS_URL,{headers:{Accept:'application/json'}});if(!response.ok)throw Error('Firebase keys unavailable');const cache=response.headers.get('cache-control')?.match(/max-age=(\d+)/),value=await response.json();keys={value,until:Date.now()+(Number(cache?.[1])||3600)*1000};return value;}
export async function verifyFirebaseIdToken(token){const parts=String(token||'').split('.');if(parts.length!==3)throw Error('Invalid token');const header=decode(parts[0]),claims=decode(parts[1]),now=Math.floor(Date.now()/1000);if(header.alg!=='RS256'||!header.kid||claims.aud!==PROJECT_ID||claims.iss!==ISSUER||typeof claims.sub!=='string'||!claims.sub||claims.sub.length>128||claims.exp<=now||claims.iat>now+60)throw Error('Invalid token');const jwk=(await publicKeys()).keys?.find(key=>key.kid===header.kid);if(!jwk)throw Error('Unknown token key');const key=await crypto.subtle.importKey('jwk',jwk,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['verify']);const valid=await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,bytes(parts[2]),new TextEncoder().encode(`${parts[0]}.${parts[1]}`));if(!valid)throw Error('Invalid token');return claims;}
export async function authenticatedAccount(request,env={}){const authorization=request.headers.get('authorization')||'';if(env.TEST_AUTH_USER&&authorization==='Bearer firebase-test-token')return {id:env.TEST_AUTH_USER,email:env.TEST_AUTH_EMAIL||'test@example.com'};const match=authorization.match(/^Bearer\s+(.+)$/i);if(!match)return null;try{const claims=await verifyFirebaseIdToken(match[1]),email=String(claims.email||'').trim().toLowerCase(),allowed=new Set(String(env.STEADY_ALLOWED_EMAILS||env.TEST_ALLOWED_EMAILS||'').split(',').map(value=>value.trim().toLowerCase()).filter(Boolean));return claims.email_verified===true&&allowed.has(email)?{id:claims.sub,email}:null;}catch{return null;}}
export async function authenticatedUser(request,env={}){return (await authenticatedAccount(request,env))?.id||null;}
