import {Inflate} from 'fflate';
import {readPrivateProfile} from './profile.mjs';
function csvLine(line){const out=[];let s='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){s+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){out.push(s);s='';}else s+=c;}out.push(s);return out;}
export function zipRows(bytes,name,visit){const data=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),decoder=new TextDecoder();let offset=0;
 while(offset+30<bytes.length&&data.getUint32(offset,true)===0x04034b50){const flags=data.getUint16(offset+6,true),method=data.getUint16(offset+8,true),size=data.getUint32(offset+18,true),n=data.getUint16(offset+26,true),extra=data.getUint16(offset+28,true),filename=decoder.decode(bytes.subarray(offset+30,offset+30+n)),start=offset+30+n+extra;if(flags&8)throw Error('Unsupported feed archive');if(filename===name){let tail='',header=null;const consume=(chunk,final)=>{tail+=decoder.decode(chunk,{stream:!final});const lines=tail.split('\n');tail=lines.pop();if(final&&tail){lines.push(tail);tail='';}for(let line of lines){line=line.replace(/\r$/,'');if(!line)continue;const values=csvLine(line);if(!header){header=values;continue;}visit(Object.fromEntries(header.map((h,i)=>[h,values[i]||''])));}};if(method===0)consume(bytes.subarray(start,start+size),true);else if(method===8){const inflate=new Inflate(consume);for(let p=start;p<start+size;p+=16384)inflate.push(bytes.subarray(p,Math.min(p+16384,start+size)),p+16384>=start+size);}else throw Error('Unsupported compression');return;}offset=start+size;}throw Error('Feed file missing: '+name);
}
const secs=s=>s.split(':').reduce((a,n)=>a*60+Number(n),0);
export function compileTimetable(bytes,config){const allowed=config?.allowedRoutes,boardCodes=[config?.outboundBoardCode,config?.inboundBoardCode],destinationCodes=[config?.outboundDestinationCode,config?.inboundDestinationCode];if(!Array.isArray(allowed)||!allowed.length||boardCodes.some(value=>!value)||destinationCodes.some(value=>!value))throw Error('Transit configuration missing');const feed=[],calendar=[],exceptions=[],trips=new Map(),stops={},ends=new Map(),boardRows=new Map(),sequences={};zipRows(bytes,'feed_info.txt',r=>feed.push(r));zipRows(bytes,'calendar.txt',r=>calendar.push(r));zipRows(bytes,'calendar_dates.txt',r=>exceptions.push(r));zipRows(bytes,'trips.txt',r=>trips.set(r.trip_id,r));zipRows(bytes,'stops.txt',r=>{stops[r.stop_id]={id:r.stop_id,code:r.stop_code,name:r.stop_name,point:[+r.stop_lat,+r.stop_lon]};});const boardIds=Object.keys(stops).filter(id=>boardCodes.includes(stops[id].code)),inboundDestinationId=Object.keys(stops).find(id=>stops[id].code===destinationCodes[1]);if(boardIds.length!==2||!inboundDestinationId)throw Error('Saved stops missing');
 zipRows(bytes,'stop_times.txt',r=>{const row={id:r.stop_id,seq:+r.stop_sequence,arrival:secs(r.arrival_time),departure:secs(r.departure_time),distance:+r.shape_dist_traveled,pickup:r.pickup_type,dropoff:r.drop_off_type},id=r.trip_id,endsFor=ends.get(id);if(!endsFor)ends.set(id,{first:row,last:row});else{if(row.seq<endsFor.first.seq)endsFor.first=row;if(row.seq>endsFor.last.seq)endsFor.last=row;}if(boardIds.includes(row.id)||row.id===inboundDestinationId){if(!boardRows.has(id))boardRows.set(id,[]);boardRows.get(id).push(row);}if(allowed.includes(trips.get(id)?.route_id))(sequences[id]??=[]).push(row);});
 const services=[],shapeIds=new Set(),usedSeq={};for(const [id,rows] of boardRows){const t=trips.get(id);if(!t)continue;for(const from of rows.filter(r=>boardIds.includes(r.id)&&r.pickup!=='1')){const direction=stops[from.id].code===boardCodes[0]?0:1,to=rows.find(r=>r.seq>from.seq&&r.dropoff!=='1'&&stops[r.id]?.code===destinationCodes[direction]);services.push({id,service:t.service_id,route:t.route_id,shape:t.shape_id,direction:to?direction:-1,from:from.id,to:to?.id||'',departure:from.departure,arrival:to?.arrival||from.departure,shapeStart:from.distance,shapeEnd:to?.distance||from.distance,headsign:t.trip_headsign});if(to&&allowed.includes(t.route_id)){shapeIds.add(t.shape_id);usedSeq[id]=(sequences[id]||[]).filter(r=>r.seq>=from.seq&&r.seq<=to.seq).sort((a,b)=>a.seq-b.seq);}}}
 const shapes={};zipRows(bytes,'shapes.txt',r=>{if(shapeIds.has(r.shape_id))(shapes[r.shape_id]??=[]).push([+r.shape_pt_lat,+r.shape_pt_lon,+r.shape_dist_traveled,+r.shape_pt_sequence]);});for(const shape of Object.values(shapes)){shape.sort((a,b)=>a[3]-b[3]);for(const p of shape)p.pop();}
 const predecessors={},blocks=new Map();for(const [id,t] of trips){if(!t.block_id||!ends.has(id))continue;const key=t.service_id+':'+t.block_id;if(!blocks.has(key))blocks.set(key,[]);blocks.get(key).push({id,route:t.route_id,...ends.get(id)});}for(const list of blocks.values()){list.sort((a,b)=>a.first.departure-b.first.departure);for(let i=1;i<list.length;i++){const a=list[i-1],b=list[i],gap=b.first.departure-a.last.arrival;if(a.last.id===b.first.id&&gap>=0&&gap<=1800&&a.route!==b.route)predecessors[b.id]={id:a.id,route:a.route,stopId:b.first.id};}}
 const neededStops=new Set([...boardIds,inboundDestinationId,...Object.values(usedSeq).flat().map(r=>r.id)]);for(const id of Object.keys(stops))if(!neededStops.has(id))delete stops[id];const neededTrips=new Set(services.filter(s=>allowed.includes(s.route)).map(s=>s.id));for(const id of Object.keys(predecessors))if(!neededTrips.has(id))delete predecessors[id];
 const f=feed[0],result={feedVersion:f.feed_version,start:f.feed_start_date,end:f.feed_end_date,calendar,exceptions,services,shapes,predecessors,stopSequences:usedSeq,stops};for(const direction of [0,1])if(!services.some(s=>s.direction===direction&&allowed.includes(s.route)&&shapes[s.shape]?.length>1))throw Error('Saved route validation failed');return result;
}
let timetablePending=null;
export async function timetableAPI(env){const db=env.DB;let row,privateProfile;try{row=await db.prepare('SELECT payload, checked_at FROM timetable_cache WHERE id = 1').first();if(row&&Date.now()-row.checked_at<86400000)return Response.json({timetable:JSON.parse(row.payload),checkedAt:row.checked_at});privateProfile=await readPrivateProfile(env);if(!privateProfile)throw Error('Private profile unavailable');if(!timetablePending)timetablePending=(async()=>{const r=await fetch('https://gtfs.adelaidemetro.com.au/v1/static/latest/google_transit.zip',{signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error('Timetable unavailable');const bytes=new Uint8Array(await r.arrayBuffer());if(bytes.length>30000000)throw Error('Feed too large');const timetable=compileTimetable(bytes,privateProfile.transitConfig),checkedAt=Date.now(),payload=JSON.stringify(timetable);if(payload.length>1900000)throw Error('Timetable exceeds cache limit');await db.prepare('INSERT INTO timetable_cache (id,payload,checked_at) VALUES (1,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,checked_at=excluded.checked_at').bind(payload,checkedAt).run();return {timetable,checkedAt};})().finally(()=>timetablePending=null);return Response.json(await timetablePending);}catch{return Response.json({timetable:row?JSON.parse(row.payload):privateProfile?.timetable||null,checkedAt:row?.checked_at||null,stale:true});}}
